### PR TITLE
NNL branch

### PR DESCRIPTION
**Pull request by sirredbeard**
This is NOT to be merged, it is for reviewing changes only.

This custom spin includes VcXsrv and weasel-pageant.

### CODE REVIEW

**Comment by grufwub** [comment]
Has this been confirmd working yet? I'm just going to run a tar gz build now but I'm unsure as to whether this way of doing things will work with weasel-pageant given the warning on their repo:
`Because WSL can only execute Win32 binaries from drvfs locations, weasel-pageant will not work if unpacked inside the WSL filesystem (onto an lxfs mount). Advanced users may place only helper.exe on drvfs, but in general it is easier to keep the pieces together.`

**Comment by grufwub** [comment]
Performed some minor adjustments to the script to get it in a working state. Though running into the following error on build (seems to be around the install epel rpm step):

./dev/
./sbin
./lib
./srv/
./bin
./proc/
./mnt/
./lost+found/
--2019-03-14 20:10:47--  https://the.earth.li/~sgtatham/putty/latest/w64/pageant.exe
Resolving the.earth.li (the.earth.li)... 46.43.34.31, 2001:41c8:10:b1f:c0ff:ee:15:900d
Connecting to the.earth.li (the.earth.li)|46.43.34.31|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://the.earth.li/~sgtatham/putty/0.70/w64/pageant.exe [following]
--2019-03-14 20:10:47--  https://the.earth.li/~sgtatham/putty/0.70/w64/pageant.exe
Reusing existing connection to the.earth.li:443.
HTTP request sent, awaiting response... 200 OK
Length: 313912 (307K) [application/x-msdos-program]
Saving to: ‘/tmp/tmp.Vo4TADg6wu/opt/pageant/pageant.exe’

100%[=====================================================>] 313,912     1.07MB/s   in 0.3s

2019-03-14 20:10:48 (1.07 MB/s) - ‘/tmp/tmp.Vo4TADg6wu/opt/pageant/pageant.exe’ saved [313912/313912]

--2019-03-14 20:10:48--  https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
Resolving dl.fedoraproject.org (dl.fedoraproject.org)... 209.132.181.24, 209.132.181.23
Connecting to dl.fedoraproject.org (dl.fedoraproject.org)|209.132.181.24|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15080 (15K) [application/x-rpm]
Saving to: ‘/tmp/tmp.Vo4TADg6wu/tmp/epel-release-latest-7.noarch.rpm’

100%[=====================================================>] 15,080      49.4KB/s   in 0.3s

2019-03-14 20:10:49 (49.4 KB/s) - ‘/tmp/tmp.Vo4TADg6wu/tmp/epel-release-latest-7.noarch.rpm’ saved [15080/15080]

error: Failed to initialize NSS library
There was a problem importing one of the Python modules
required to run yum. The error leading to this problem was:

   cannot import name ts

Please install a package which provides this module, or
verify that the module is installed correctly.

It's possible that the above module doesn't match the
current version of Python, which is:
2.7.5 (default, Oct 30 2018, 23:45:53)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

If you cannot solve this problem yourself, please go to
the yum faq at:
  http://yum.baseurl.org/wiki/Faq

**Comment by sirredbeard** [comment]
#26 should fix above as chroot prevents access to /dev/urandom needed by gpg

**Comment by grufwub** [comment]
Made a PR fixing up create-targz and firstrun. Only issue now is that firstrun only works if run from root. Might be worth adding sudo to the install image under create-targz, then we can modify firstrun to actually work? And we could set the initial install to only ask for a user password that way, as we already do on regular Pengwin? @sirredbeard

**Pull request closed without merging**
